config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  get "sign_in" => "sessions#new"
  post "sign_in" => "sessions#create"
  delete "sign_out" => "sessions#destroy"

  get "stories" => "stories#index"
  post "stories" => "stories#save"
  get "stories/new" => "stories#new"
  get "stories/:id" => "stories#edit"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :story
  belongs_to :user
end

app/models/organization.rb
class Organization < ApplicationRecord
  validates :slug, presence: true, format: { with: /[a-z0-9]{3,10}/, message: "Bad Format" }, length: { minimum: 3, maximum: 10, message: "Should have at least three letters and ten at maximum" }, uniqueness: { case_sensitive: false }
  validates :name, presence: true, length: { minimum: 3, message: "Should have at least three letters" }

  before_save :downcase_slug

  def downcase_slug
    self.slug.downcase!
  end
end

app/models/story.rb
class Story < ApplicationRecord
  validates :headline, presence: true, length: { minimum: 10, message: "Should have at least ten characters" }
  validates :status, presence: true, inclusion: { in: %w(unassigned draft for_review in_review pending approved published archived) }
  belongs_to :organization
  belongs_to :writer, optional: true
  belongs_to :reviewer, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: true, length: { minimum: 6, message: "Should have at least six characters" }
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, message: "Bad Format" }, uniqueness: { case_sensitive: false }
  validates :role, presence: true, inclusion: { in: %w(editor writer) }
  belongs_to :organization

  before_save :downcase_email

  def downcase_email
    self.email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authorize
    unless signed_in?
      redirect_to "/"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :block_access, except: [:destroy]

  def create
    @organization = Organization.find_by(slug: params[:session][:organization].downcase)
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      sign_in
      redirect_to "/stories"
    else
      render "new"
    end
  end

  def destroy
    sign_out
    redirect_to "/"
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authorize

  def initialize
    @users = User.all
  end

  def save
    puts @story

    status = if params[:story][:status] != nil
        params[:story][:status]
      elsif params[:story][:reviewer_id] != "" && params[:story][:writer_id] != ""
        "for_review"
      elsif params[:story][:writer_id] != ""
        "draft"
      else
        "unassigned"
      end

    if params[:story][:id] == nil
      @story = Story.new(headline: params[:story][:headline], organization: current_user.organization, status: status, writer_id: params[:story][:writer_id], reviewer_id: params[:story][:reviewer_id])
      @story.save
    else
      @story = Story.find(params[:story][:id])
      @story.update(body: params[:story][:body], status: status, writer_id: params[:story][:writer_id], reviewer_id: params[:story][:reviewer_id])
    end

    redirect_to "/stories"
  end

  def index
    @stories = Story.all
  end

  def edit
    @story = Story.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in
    session[:user_id] = @user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def block_access
    if current_user.present?
      redirect_to "/stories"
    end
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/_header.html.erb
<header>
  <div>
    <nav>
      <ul>
        <% if signed_in? %>
          <li>
            <ul>
              <li>
                <%= link_to "Log out", sign_out_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", root_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/stories/edit.html.erb
<%= form_for :story, url: stories_path do |f| %>
    <%= f.hidden_field :id, :value => @story.id %>

    <div class="field">
        <%= f.label :headline %><br />
        <%= f.text_field :headline, autofocus: true, :minlength => 10 %>
    </div>

    <div class="field">
        <%= f.label :body %><br />
        <%= f.text_area :body, autofocus: true %>
    </div>

    <div class="field">
        <%= f.label :writer %><br />
        <%= f.select :writer_id, @users.collect { |user| [user.email, user.id] }, :include_blank => true %>
    </div>   

    <div class="field">
        <%= f.label :reviewer %><br />
        <%= f.select :reviewer_id, @users.collect { |user| [user.email, user.id] }, :include_blank => true %>
    </div>   
    
    <div class="actions">
        <%= f.submit "Save" %>
    </div>
<% end %>

app/views/stories/index.html.erb
<h1> Stories </h1>
<% if current_user.role == "editor" %>
    <%= link_to "New Story", stories_new_path %>
<% end %>
<table>
    <thead>
      <tr>
        <th>Id</th>
        <th>Headline</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @stories.each do |story| %>
        <tr>
          <td><%= story.id %></td>
          <td><%= story.headline %></td>
          <td><%= story.status %></td>
        </tr>
     <% end %>
   </tbody>
</table>

app/views/stories/new.html.erb
<%= form_for :story, url: stories_path do |f| %>
    <div class="field">
        <%= f.label :headline %><br />
        <%= f.text_field :headline, autofocus: true, :minlength => 10 %>
    </div>

    <div class="field">
        <%= f.label :writer %><br />
        <%= f.select :writer_id, @users.collect { |user| [user.email, user.id] }, :include_blank => true %>
    </div>   

    <div class="field">
        <%= f.label :reviewer %><br />
        <%= f.select :reviewer_id, @users.collect { |user| [user.email, user.id] }, :include_blank => true %>
    </div>   
    
    <div class="actions">
        <%= f.submit "Save" %>
    </div>
<% end %>